spring:
  application:
    name: authserver
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /api

spring-doc:
  swagger-ui:
    use-root-path: true

aws:
  region: ${AWS_REGION:us-east-1}
  bucket: ${AWS_S3_BUCKET:}
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_SECRET_ACCESS_KEY:}
  endpoint: ${AWS_S3_ENDPOINT:}



